[package]
name = "detree"
version = "1.1.0"
edition = "2021"
rust-version = "1.81"
authors = ["Morgan Ross <morganross@rossmorr.com>"]
description = "Convert tree lists or JSON into directories & Markdown files"
license = "MIT"
repository = "https://github.com/morganross/detree3"
homepage = "https://github.com/morganross/detree3"
readme = "README.md"
keywords = ["cli", "markdown", "docusaurus", "filesystem", "generator"]
categories = ["command-line-utilities", "filesystem"]
exclude = ["/target", "/dist"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
